# Generated by Django 5.2.16 on 2026-08-05 00:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1ere', '1ère'), ('terminale', 'Terminale'), ('both', 'Both')], max_length=10)),
                ('group_tier', models.CharField(choices=[('GROUP_10', 'Group of 10'), ('GROUP_5', 'Group of 5'), ('GROUP_3', 'Group of 3'), ('INDIVIDUAL', 'Individual')], max_length=12)),
                ('weekly_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('response', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (croissant).")),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1ere', '1ère'), ('terminale', 'Terminale'), ('both', 'Both')], max_length=10)),
                ('group_tier', models.CharField(choices=[('GROUP_10', 'Group of 10'), ('GROUP_5', 'Group of 5'), ('GROUP_3', 'Group of 3'), ('INDIVIDUAL', 'Individual')], max_length=12)),
                ('weekly_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('awaiting_schedule', "Awaiting teacher's schedule"), ('scheduled', 'At least one slot scheduled')], default='awaiting_schedule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_tier', models.CharField(choices=[('GROUP_10', 'Groupe de 10'), ('GROUP_5', 'Groupe de 5'), ('GROUP_3', 'Groupe de 3'), ('INDIVIDUAL', 'Individuel')], max_length=12, unique=True)),
                ('price_per_hour_cents', models.PositiveIntegerField(help_text="Prix en centimes d'euro, par heure de cours.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('mentions-legales', 'Mentions légales'), ('cgv', 'Conditions générales de vente'), ('confidentialite', 'Politique de confidentialité')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Texte brut — un paragraphe par ligne vide.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('level', models.CharField(choices=[('1ere', '1ère'), ('terminale', 'Terminale'), ('both', 'Both')], default='both', max_length=10)),
                ('bac_type', models.CharField(choices=[('general', 'Général'), ('techno', 'Technologique'), ('pro', 'Professionnel')], default='general', max_length=10)),
                ('subject_type', models.CharField(choices=[('common_core', 'Tronc commun'), ('specialty', 'Spécialité')], default='specialty', max_length=15)),
                ('hours_per_week_premiere', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('hours_per_week_terminale', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('1ere', '1ère'), ('terminale', 'Terminale')], max_length=10)),
                ('chapter_name', models.CharField(max_length=150)),
                ('video_provider_id', models.CharField(help_text='ID/URL reference in the streaming provider (e.g. Cloudflare Stream UID).', max_length=200)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['level', 'chapter_name', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1ere', '1ère'), ('terminale', 'Terminale'), ('both', 'Both')], max_length=10)),
                ('group_tier', models.CharField(choices=[('GROUP_10', 'Group of 10'), ('GROUP_5', 'Group of 5'), ('GROUP_3', 'Group of 3'), ('INDIVIDUAL', 'Individual')], max_length=12)),
                ('max_capacity', models.PositiveSmallIntegerField()),
                ('min_students', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_enrollment_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('assigned', 'Teacher assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('meeting_url', models.URLField(blank=True)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('recording_url', models.URLField(blank=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.classseries')),
                ('group_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sessions', to='core.groupassignment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.subject')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('waitlisted', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_at'],
                'unique_together': {('student', 'class_session')},
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1ere', '1ère'), ('terminale', 'Terminale'), ('both', 'Both')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='core.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_accepted_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.forumthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_announcements', to=settings.AUTH_USER_MODEL)),
                ('group_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.groupassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classseries',
            name='group_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_series', to='core.groupassignment'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('document', 'Document (PDF, etc.)'), ('video_link', 'Lien vidéo')], default='document', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, upload_to='materials/%Y/%m/')),
                ('url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.classsession')),
                ('group_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.groupassignment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], default='pending', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bac_type', models.CharField(choices=[('general', 'Général'), ('techno', 'Technologique'), ('pro', 'Professionnel')], default='general', max_length=10)),
                ('grade_level', models.CharField(choices=[('1ere', '1ère'), ('terminale', 'Terminale')], max_length=10)),
                ('candidate_type', models.CharField(choices=[('standard', 'Standard high school'), ('candidat_libre', 'Candidat libre')], default='standard', max_length=20)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=64)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_default_payment_method_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('premiere_specialties', models.ManyToManyField(blank=True, help_text='Up to 3 specialty subjects chosen for Première.', related_name='students_specialty_1ere', to='core.subject')),
                ('terminale_specialties', models.ManyToManyField(blank=True, help_text='Up to 2 specialty subjects kept for Terminale.', related_name='students_specialty_terminale', to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1ere', '1ère'), ('terminale', 'Terminale'), ('both', 'Both')], max_length=10)),
                ('group_tier', models.CharField(choices=[('GROUP_10', 'Group of 10'), ('GROUP_5', 'Group of 5'), ('GROUP_3', 'Group of 3'), ('INDIVIDUAL', 'Individual')], max_length=12)),
                ('weekly_hours', models.PositiveSmallIntegerField(blank=True, choices=[(1, '4h/mois'), (2, '8h/mois'), (6, '6h/semaine'), (8, '8h/semaine'), (12, '12h/semaine'), (16, '16h/semaine'), (24, '24h/semaine')], null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('teacher_assigned', 'Assigned to a teacher, awaiting their schedule'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.groupassignment')),
                ('resulting_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='core.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to='core.subject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_assignments', to='core.subject'),
        ),
        migrations.AddField(
            model_name='classseries',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='core.subject'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=12)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('current_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('compensation_type', models.CharField(choices=[('flat_per_session', 'Flat per session'), ('per_student', 'Per student present'), ('percentage', 'Percentage of revenue')], default='flat_per_session', max_length=20)),
                ('compensation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_meeting_url', models.URLField(blank=True, help_text='Lien de visioconférence personnel (Google Meet, Zoom, Teams...), réutilisé par défaut pour les séances que cet enseignant planifie lui-même.')),
                ('google_account_email', models.EmailField(blank=True, help_text='Set automatically once the teacher connects their Google account.', max_length=254)),
                ('google_oauth_refresh_token', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='teacher_photos/%Y/%m/')),
                ('title_degree', models.CharField(blank=True, help_text='Diplôme ou titre affiché publiquement, ex: "Doctorante en Physique", "17 ans d\'exp. Éducation Nationale".', max_length=200)),
                ('bio_short', models.CharField(blank=True, help_text="Phrase d'accroche / citation courte affichée sur la carte enseignant.", max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher cet enseignant sur la page d'accueil.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, help_text='Matière principale mise en avant sur la landing page (ex: Mathématiques).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.teacherprofile')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.teacherprofile')),
            ],
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='classseries',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_series', to='core.teacherprofile'),
        ),
        migrations.CreateModel(
            name='SeriesMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('leaving', 'Leaving (ends this month)'), ('left', 'Left')], default='active', max_length=10)),
                ('monthly_price_cents', models.PositiveIntegerField(help_text='Snapshot of the monthly rate at signup, in cents.')),
                ('is_billable', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('leave_requested_at', models.DateTimeField(blank=True, null=True)),
                ('leaves_on', models.DateTimeField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.classseries')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'series')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.teacherprofile')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='core.videocapsule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'capsule')},
            },
        ),
    ]
