# Generated by Django 5.2.17 on 2026-08-17 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_referral_codes(apps, schema_editor):
    """
    Donne un code unique à chaque compte déjà existant, AVANT que la
    contrainte unique ne soit appliquée juste après — sans ça, tous les
    comptes existants se retrouveraient avec le même champ vide et la
    contrainte échouerait immédiatement (c'est exactement ce qui a causé
    le lien de parrainage cassé "ref=null" observé précédemment).
    Même logique que User._generate_referral_code(), réécrite ici car une
    migration ne doit jamais dépendre du code du modèle "vivant" (qui
    changera dans le futur) — seulement de l'état figé au moment de cette
    migration.
    """
    import random
    import string

    User = apps.get_model("core", "User")
    alphabet = string.ascii_uppercase + string.digits
    for user in User.objects.all():
        if user.referral_code:
            continue
        while True:
            candidate = "".join(random.choices(alphabet, k=8))
            if not User.objects.filter(referral_code=candidate).exists():
                user.referral_code = candidate
                user.save(update_fields=["referral_code"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_full_name', models.CharField(max_length=150)),
                ('parent_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé')], default='confirmed', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('konnect', 'Konnect')], default='stripe', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='konnect_payment_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='pricingrate',
            name='price_per_hour_millimes_tnd',
            field=models.PositiveIntegerField(default=0, help_text='Prix en millimes de dinar tunisien (1 DT = 1000 millimes), par heure de cours — marché tunisien (Konnect).'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='terminale_math_option',
            field=models.ForeignKey(blank=True, help_text='Maths Expertes ou Maths Complémentaires, au choix (Terminale uniquement).', limit_choices_to={'subject_type': 'math_option'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_math_option', to='core.subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(_backfill_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classseries',
            name='group_tier',
            field=models.CharField(choices=[('GROUP_10', 'Group of 10'), ('GROUP_6', 'Group of 6'), ('GROUP_5', 'Group of 5'), ('GROUP_4', 'Group of 4'), ('GROUP_3', 'Group of 3'), ('GROUP_2', 'Group of 2'), ('INDIVIDUAL', 'Individual')], max_length=12),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='group_tier',
            field=models.CharField(choices=[('GROUP_10', 'Group of 10'), ('GROUP_6', 'Group of 6'), ('GROUP_5', 'Group of 5'), ('GROUP_4', 'Group of 4'), ('GROUP_3', 'Group of 3'), ('GROUP_2', 'Group of 2'), ('INDIVIDUAL', 'Individual')], max_length=12),
        ),
        migrations.AlterField(
            model_name='groupassignment',
            name='group_tier',
            field=models.CharField(choices=[('GROUP_10', 'Group of 10'), ('GROUP_6', 'Group of 6'), ('GROUP_5', 'Group of 5'), ('GROUP_4', 'Group of 4'), ('GROUP_3', 'Group of 3'), ('GROUP_2', 'Group of 2'), ('INDIVIDUAL', 'Individual')], max_length=12),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='group_tier',
            field=models.CharField(choices=[('GROUP_10', 'Group of 10'), ('GROUP_6', 'Group of 6'), ('GROUP_5', 'Group of 5'), ('GROUP_4', 'Group of 4'), ('GROUP_3', 'Group of 3'), ('GROUP_2', 'Group of 2'), ('INDIVIDUAL', 'Individual')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pricingrate',
            name='group_tier',
            field=models.CharField(choices=[('GROUP_10', 'Groupe de 10'), ('GROUP_6', 'Groupe de 6'), ('GROUP_5', 'Groupe de 5'), ('GROUP_4', 'Groupe de 4'), ('GROUP_3', 'Groupe de 3'), ('GROUP_2', 'Groupe de 2'), ('INDIVIDUAL', 'Individuel')], max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('common_core', 'Tronc commun'), ('specialty', 'Spécialité'), ('math_option', 'Option mathématiques (Terminale)')], default='specialty', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('affiliate', 'Affiliate')], default='student', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(fields=('teacher', 'period_start', 'period_end', 'currency'), name='unique_payout_per_teacher_period_currency'),
        ),
        migrations.AddField(
            model_name='parentalconsent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parental_consent', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission', to='core.payment'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions_earned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions_generated', to=settings.AUTH_USER_MODEL),
        ),
    ]
