# Generated by Django 5.2.17 on 2026-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parentalconsent_referralcommission_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cecrl_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 — Découverte'), ('A2', 'A2 — Survie'), ('B1', 'B1 — Seuil'), ('B2', 'B2 — Avancé'), ('C1', 'C1 — Autonome'), ('C2', 'C2 — Maîtrise')], max_length=2),
        ),
        migrations.AddField(
            model_name='subject',
            name='cecrl_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 — Découverte'), ('A2', 'A2 — Survie'), ('B1', 'B1 — Seuil'), ('B2', 'B2 — Avancé'), ('C1', 'C1 — Autonome'), ('C2', 'C2 — Maîtrise')], max_length=2),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bac_type',
            field=models.CharField(choices=[('general', 'Général'), ('techno', 'Technologique'), ('pro', 'Professionnel'), ('fle', 'FLE — Français Langue Étrangère'), ('fls', 'FLS — Français Langue Seconde')], default='general', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('1ere', '1ère'), ('terminale', 'Terminale')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='bac_type',
            field=models.CharField(choices=[('general', 'Général'), ('techno', 'Technologique'), ('pro', 'Professionnel'), ('fle', 'FLE — Français Langue Étrangère'), ('fls', 'FLS — Français Langue Seconde')], default='general', max_length=10),
        ),
    ]
