# Generated by Django 5.2.17 on 2026-08-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_selfstudyplan_price_tnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('konnect', 'Konnect'), ('bank_transfer', 'Virement bancaire (manuel)')], default='stripe', max_length=15),
        ),
        migrations.AlterField(
            model_name='selfstudyplan',
            name='code',
            field=models.CharField(choices=[('premiere_non_spe', '1ère — Tronc commun (non spécialité)'), ('premiere_spe', '1ère — Spécialité Mathématiques'), ('premiere_techno', '1ère Technologique'), ('terminale_spe', 'Terminale — Spécialité Mathématiques'), ('terminale_maths_expertes', 'Terminale — Mathématiques Expertes'), ('terminale_maths_complementaires', 'Terminale — Mathématiques Complémentaires')], max_length=35, unique=True),
        ),
    ]
