# Generated by Django 5.2.16 on 2026-08-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
