# Generated by Django 5.2.16 on 2026-08-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_newslettersubscriber_id'),
        ('core', '0010_classsession_preferred_teacher'),
    ]

    operations = [
    ]
